services:

  deal_db:
    container_name: deal_db
    image: 'postgres:latest'
    user: root
    environment:
      - POSTGRES_DB=creditbank
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
      - PORT=8870
    ports:
      - 8870:8870
    command: -p 8870
    networks:
      - creditbank_network
  deal-service:
    container_name: deal_service
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - deal_db
    networks:
      - creditbank_network
networks:
  creditbank_network:
    driver: bridge
    name: creditbank_network

  