spring:
  liquibase:
    change-log: classpath:db/migrations/changelog.xml
    enabled: true
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:8001/profiles}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:example}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

links:
  urls:
    calculator-host: ${CALCULATOR_HOST_URL:http://localhost:8080}
    calculator/offers: calculator/offers
    calculator/calc: calculator/calc
server:
  port: 8081