name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - develop
      - "feature/*"
      

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: eclipse-temurin:17-jdk
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          apt-get update
          apt-get install -y curl
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
      - name: Install Maven
        run: |
          apt-get update
          apt-get install -y maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up
      - name: Wait for services
        run: sleep
      - name: Check Running Containers
        run: docker ps
