name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - develop
      

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: docker:20.10.7
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          maven-version: '3.8.6'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up
      - name: Wait for services
        run: sleep
      - name: Check Running Containers
        run: docker ps
